name: Publish new release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

jobs:

  build_chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Bump package version to ${{ inputs.version }}
        run: |
          VERSION="${{ inputs.version }}"
          jq --arg version "$VERSION" '.version = $version' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Install dependencies
        run: npm install -g yarn && yarn

      - name: Build Chrome Extension ${{ inputs.version }}
        run: yarn plasmo build --target=chrome-mv3 --zip

      - name: Create key.pem ${{ inputs.version }}
        env:
          CRX_KEY: ${{ secrets.CRX_KEY }}
        run: echo "$CRX_KEY" > key.pem

      - name: Package Chrome Extension ${{ inputs.version }}
        run: >
          yarn crx3
          --keyPath key.pem
          --zipPath "./release/7speaking-bot-rework_chrome-${{ inputs.version }}.zip"
          --crxPath "./release/7speaking-bot-rework_chrome-${{ inputs.version }}.crx"
          --xmlPath "./release/chrome_update.xml"
          --crxUrl "https://github.com/orkeilius/7speaking-bot-rework/releases/download/${{ inputs.version }}/7speaking-bot-rework_chromium-${{ inputs.version }}.crx"
          "./build/chrome-mv3-prod/manifest.json"

      - name: Upload Chrome Extension ${{ inputs.version }} zip
        uses: actions/upload-artifact@v4
        with:
          path: "./release/7speaking-bot-rework_chrome-${{ inputs.version }}.zip"
          name: 7speaking-bot-rework_chrome-${{ inputs.version }}.zip
      - name: Upload Chrome Extension ${{ inputs.version }} crx
        uses: actions/upload-artifact@v4
        with:
          path: "./release/7speaking-bot-rework_chrome-${{ inputs.version }}.crx"
          name: 7speaking-bot-rework_chrome-${{ inputs.version }}.crx
      - name: Upload Chrome metadata ${{ inputs.version }}
        uses: actions/upload-artifact@v4
        with:
          path: "./release/chrome_update.xml"
          name: chrome_update_${{ inputs.version }}

  build_firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Bump package version to ${{ inputs.version }}
        run: |
          VERSION="${{ inputs.version }}"
          jq --arg version "$VERSION" '.version = $version' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Install dependencies
        run: npm install -g yarn && yarn


      - name: Build Firefox Extension ${{ inputs.version }}
        run: yarn plasmo build --target=firefox-mv3 --zip


      - name: Upload Firefox unsigned Extension ${{ inputs.version }} zip
        uses: actions/upload-artifact@v4
        with:
          path: "./build/firefox-mv3-prod.zip"
          name: 7speaking-bot-rework_firefox-${{ inputs.version }}-unsigned

  sign_firefox:
    runs-on: ubuntu-latest
    needs: build_firefox
    env:
      FIREFOX_ID: 7speaking-bot-rework@github.com
      FIREFOX_API_KEY: ${{ secrets.FIREFOX_API_KEY }}
      FIREFOX_API_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
      FIREFOX_TAG: ${{ inputs.version }}
      INPUT_PATH: ./build/firefox-mv3-prod.zip
      OUTPUT_PATH: ./7speaking-bot-rework_firefox-${{ inputs.version }}.xpi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install -g yarn && yarn

      - name: Download Firefox unsigned Extension ${{ inputs.version }}
        uses: actions/download-artifact@v4
        with:
          name: 7speaking-bot-rework_firefox-${{ inputs.version }}-unsigned
          path: "./build/"

      - name: Upload signed firefox extension ${{ inputs.version }}
        run: node ./script/upload-firefox.js

      - name: Wait for signing
        run: node ./script/wait-for-signing.js

      - name: Download signed Firefox Extension ${{ inputs.version }}
        run: |
          sleep 10
          node ./script/download-signed-firefox.js

      - name: Upload signed Firefox Extension ${{ inputs.version }}
        uses: actions/upload-artifact@v4
        with:
          path: ./7speaking-bot-rework_firefox-${{ inputs.version }}.xpi
          name: 7speaking-bot-rework_firefox-${{ inputs.version }}.xpi

  update-repo:
    runs-on: ubuntu-latest
    needs:
      - build_chrome
      - sign_firefox
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install -g yarn && yarn

      - name: Download chrome metadata
        uses: actions/download-artifact@v4
        with:
          name: chrome_update_${{ inputs.version }}
          path: "./release/chrome_update.xml.tmp"

      - name: update package to version ${{ inputs.version }}
        run: |
          VERSION="${{ inputs.version }}"
          jq --arg version "$VERSION" '.version = $version' package.json > package.json.tmp
          mv package.json.tmp package.json
          mv ./release/chrome_update.xml.tmp ./release/chrome_update.xml 

      - name: Update firefox_update.json ${{ inputs.version }}
        run: |
          VERSION="${{ inputs.version }}"
          FIREFOX_ID="7speaking-bot-rework@github.com"
          UPDATE_LINK="https://github.com/orkeilius/7speaking-bot-rework/releases/download/${{ inputs.version }}/7speaking-bot-rework_firefox-${{ inputs.version }}.xpi"
          jq --arg version "$VERSION" \
             --arg firefox_id "$FIREFOX_ID" \
             --arg update_link "$UPDATE_LINK" \
             '.addons[$firefox_id].updates += [{"version": $version, "update_link": $update_link}]' \
             release/firefox_update.json > release/firefox_update.json.tmp
          mv release/firefox_update.json.tmp release/firefox_update.json

      - name: Commit update
        uses: EndBug/add-and-commit@v10

